# -*- coding: utf-8 -*-


"""
Django settings for eazyliner project.

Generated by 'django-admin startproject' using Django 1.10.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 't-+%v0q#mrbxuux^s16&3tmo1owe*@ys4igi_#_(xc^jz35l=_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

ADMINS = [
    ('Francisco A. Galván Báez', 'fgalvan@outlook.com'),
]

MANAGERS = ADMINS

SEND_BROKEN_LINK_EMAILS = False


# Application definition
PREREQ_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

]

THIRD_PARTY_APPS = [
    'djangobower',
    'rest_framework'
]

PROJECT_APPS = [
    'data_rest',
]

INSTALLED_APPS = PREREQ_APPS + THIRD_PARTY_APPS + PROJECT_APPS


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    #Custom middleware

]

ROOT_URLCONF = 'eazyliner.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'eazyliner.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

#Statics comunes para varias apps
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static-common"),
    #os.path.join(BASE_DIR, "mediaroot"),
]

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'djangobower.finders.BowerFinder',
]

#STATIC_ROOT = os.path.join(BASE_DIR, 'staticroot')
#MEDIA_ROOT = os.path.join(BASE_DIR, 'mediaroot')
STATIC_URL = '/static/'
MEDIA_URL = '/media/'



#BOWER
BOWER_COMPONENTS_ROOT = os.path.join(BASE_DIR, 'bower_components')
#BOWER_PATH = '../venv_eazyliner/lib/python2.7/site-packages/djangobower/bower'
BOWER_INSTALLED_APPS = [
    'jquery',
    'iron-flex-layout',
    'iron-icon',
    'iron-icons',
    'iron-iconset-svg',
    'iron-meta',
    'webcomponentsjs',
    'paper-drawer-panel',
    "paper-header-panel", #: "PolymerElements/paper-header-panel",
    "paper-item", #: "PolymerElements/paper-item",
    "paper-material", #: "PolymerElements/paper-material",
    "paper-menu", #: "PolymerElements/paper-menu",
    "paper-toolbar", #: "PolymerElements/paper-toolbar",
    "paper-dialog", #: "PolymerElements/paper-dialog",
    "paper-input", #: "PolymerElements/paper-input",
    "paper-button", #: "PolymerElements/paper-button",
    "paper-icon-button", #: "PolymerElements/paper-icon-button",
    "paper-card", #: "PolymerElements/paper-card",

    "iron-icons", #: "PolymerElements/iron-icons",
    "iron-form", #: "PolymerElements/iron-form",
    "iron-ajax", #: "PolymerElements/iron-ajax",
    "iron-flex-layout", #: "PolymerElements/iron-flex-layout",

    "paper-date-picker", #: "bendavis78/paper-date-picker"
]


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # 'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    )
}
